// ISO 3166-1 alpha-3 country list, sorted by display name. Used in any
// country-picking dropdown so we have one consistent vocabulary across forms.
//
// Project convention: the UAE is stored as `DXB` (not the ISO `ARE`) because
// the team aligns invoices and tracking with Dubai's airport / port code.
// `normalizeCountryCode` always converts a stored `ARE` into `DXB` so legacy
// records still display correctly.
export interface CountryOption {
  code: string; // alpha-3 (DXB for UAE — see note above)
  name: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: 'AFG', name: 'Afghanistan' },
  { code: 'ALB', name: 'Albania' },
  { code: 'DZA', name: 'Algeria' },
  { code: 'AND', name: 'Andorra' },
  { code: 'AGO', name: 'Angola' },
  { code: 'ATG', name: 'Antigua and Barbuda' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armenia' },
  { code: 'AUS', name: 'Australia' },
  { code: 'AUT', name: 'Austria' },
  { code: 'AZE', name: 'Azerbaijan' },
  { code: 'BHS', name: 'Bahamas' },
  { code: 'BHR', name: 'Bahrain' },
  { code: 'BGD', name: 'Bangladesh' },
  { code: 'BRB', name: 'Barbados' },
  { code: 'BLR', name: 'Belarus' },
  { code: 'BEL', name: 'Belgium' },
  { code: 'BLZ', name: 'Belize' },
  { code: 'BEN', name: 'Benin' },
  { code: 'BTN', name: 'Bhutan' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'BIH', name: 'Bosnia and Herzegovina' },
  { code: 'BWA', name: 'Botswana' },
  { code: 'BRA', name: 'Brazil' },
  { code: 'BRN', name: 'Brunei' },
  { code: 'BGR', name: 'Bulgaria' },
  { code: 'BFA', name: 'Burkina Faso' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'CPV', name: 'Cabo Verde' },
  { code: 'KHM', name: 'Cambodia' },
  { code: 'CMR', name: 'Cameroon' },
  { code: 'CAN', name: 'Canada' },
  { code: 'CAF', name: 'Central African Republic' },
  { code: 'TCD', name: 'Chad' },
  { code: 'CHL', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'COL', name: 'Colombia' },
  { code: 'COM', name: 'Comoros' },
  { code: 'COG', name: 'Congo' },
  { code: 'COD', name: 'Congo (Democratic Republic)' },
  { code: 'CRI', name: 'Costa Rica' },
  { code: 'CIV', name: "Côte d'Ivoire" },
  { code: 'HRV', name: 'Croatia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'CYP', name: 'Cyprus' },
  { code: 'CZE', name: 'Czechia' },
  { code: 'DNK', name: 'Denmark' },
  { code: 'DJI', name: 'Djibouti' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'DOM', name: 'Dominican Republic' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'EGY', name: 'Egypt' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'GNQ', name: 'Equatorial Guinea' },
  { code: 'ERI', name: 'Eritrea' },
  { code: 'EST', name: 'Estonia' },
  { code: 'SWZ', name: 'Eswatini' },
  { code: 'ETH', name: 'Ethiopia' },
  { code: 'FJI', name: 'Fiji' },
  { code: 'FIN', name: 'Finland' },
  { code: 'FRA', name: 'France' },
  { code: 'GAB', name: 'Gabon' },
  { code: 'GMB', name: 'Gambia' },
  { code: 'GEO', name: 'Georgia' },
  { code: 'DEU', name: 'Germany' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'GRC', name: 'Greece' },
  { code: 'GRD', name: 'Grenada' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'GIN', name: 'Guinea' },
  { code: 'GNB', name: 'Guinea-Bissau' },
  { code: 'GUY', name: 'Guyana' },
  { code: 'HTI', name: 'Haiti' },
  { code: 'HND', name: 'Honduras' },
  { code: 'HKG', name: 'Hong Kong' },
  { code: 'HUN', name: 'Hungary' },
  { code: 'ISL', name: 'Iceland' },
  { code: 'IND', name: 'India' },
  { code: 'IDN', name: 'Indonesia' },
  { code: 'IRN', name: 'Iran' },
  { code: 'IRQ', name: 'Iraq' },
  { code: 'IRL', name: 'Ireland' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italy' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'JPN', name: 'Japan' },
  { code: 'JOR', name: 'Jordan' },
  { code: 'KAZ', name: 'Kazakhstan' },
  { code: 'KEN', name: 'Kenya' },
  { code: 'KIR', name: 'Kiribati' },
  { code: 'KWT', name: 'Kuwait' },
  { code: 'KGZ', name: 'Kyrgyzstan' },
  { code: 'LAO', name: 'Laos' },
  { code: 'LVA', name: 'Latvia' },
  { code: 'LBN', name: 'Lebanon' },
  { code: 'LSO', name: 'Lesotho' },
  { code: 'LBR', name: 'Liberia' },
  { code: 'LBY', name: 'Libya' },
  { code: 'LIE', name: 'Liechtenstein' },
  { code: 'LTU', name: 'Lithuania' },
  { code: 'LUX', name: 'Luxembourg' },
  { code: 'MAC', name: 'Macao' },
  { code: 'MDG', name: 'Madagascar' },
  { code: 'MWI', name: 'Malawi' },
  { code: 'MYS', name: 'Malaysia' },
  { code: 'MDV', name: 'Maldives' },
  { code: 'MLI', name: 'Mali' },
  { code: 'MLT', name: 'Malta' },
  { code: 'MHL', name: 'Marshall Islands' },
  { code: 'MRT', name: 'Mauritania' },
  { code: 'MUS', name: 'Mauritius' },
  { code: 'MEX', name: 'Mexico' },
  { code: 'FSM', name: 'Micronesia' },
  { code: 'MDA', name: 'Moldova' },
  { code: 'MCO', name: 'Monaco' },
  { code: 'MNG', name: 'Mongolia' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'MAR', name: 'Morocco' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'MMR', name: 'Myanmar' },
  { code: 'NAM', name: 'Namibia' },
  { code: 'NRU', name: 'Nauru' },
  { code: 'NPL', name: 'Nepal' },
  { code: 'NLD', name: 'Netherlands' },
  { code: 'NZL', name: 'New Zealand' },
  { code: 'NIC', name: 'Nicaragua' },
  { code: 'NER', name: 'Niger' },
  { code: 'NGA', name: 'Nigeria' },
  { code: 'PRK', name: 'North Korea' },
  { code: 'MKD', name: 'North Macedonia' },
  { code: 'NOR', name: 'Norway' },
  { code: 'OMN', name: 'Oman' },
  { code: 'PAK', name: 'Pakistan' },
  { code: 'PLW', name: 'Palau' },
  { code: 'PSE', name: 'Palestine' },
  { code: 'PAN', name: 'Panama' },
  { code: 'PNG', name: 'Papua New Guinea' },
  { code: 'PRY', name: 'Paraguay' },
  { code: 'PER', name: 'Peru' },
  { code: 'PHL', name: 'Philippines' },
  { code: 'POL', name: 'Poland' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'QAT', name: 'Qatar' },
  { code: 'ROU', name: 'Romania' },
  { code: 'RUS', name: 'Russia' },
  { code: 'RWA', name: 'Rwanda' },
  { code: 'KNA', name: 'Saint Kitts and Nevis' },
  { code: 'LCA', name: 'Saint Lucia' },
  { code: 'VCT', name: 'Saint Vincent and the Grenadines' },
  { code: 'WSM', name: 'Samoa' },
  { code: 'SMR', name: 'San Marino' },
  { code: 'STP', name: 'São Tomé and Príncipe' },
  { code: 'SAU', name: 'Saudi Arabia' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SRB', name: 'Serbia' },
  { code: 'SYC', name: 'Seychelles' },
  { code: 'SLE', name: 'Sierra Leone' },
  { code: 'SGP', name: 'Singapore' },
  { code: 'SVK', name: 'Slovakia' },
  { code: 'SVN', name: 'Slovenia' },
  { code: 'SLB', name: 'Solomon Islands' },
  { code: 'SOM', name: 'Somalia' },
  { code: 'ZAF', name: 'South Africa' },
  { code: 'KOR', name: 'South Korea' },
  { code: 'SSD', name: 'South Sudan' },
  { code: 'ESP', name: 'Spain' },
  { code: 'LKA', name: 'Sri Lanka' },
  { code: 'SDN', name: 'Sudan' },
  { code: 'SUR', name: 'Suriname' },
  { code: 'SWE', name: 'Sweden' },
  { code: 'CHE', name: 'Switzerland' },
  { code: 'SYR', name: 'Syria' },
  { code: 'TWN', name: 'Taiwan' },
  { code: 'TJK', name: 'Tajikistan' },
  { code: 'TZA', name: 'Tanzania' },
  { code: 'THA', name: 'Thailand' },
  { code: 'TLS', name: 'Timor-Leste' },
  { code: 'TGO', name: 'Togo' },
  { code: 'TON', name: 'Tonga' },
  { code: 'TTO', name: 'Trinidad and Tobago' },
  { code: 'TUN', name: 'Tunisia' },
  { code: 'TUR', name: 'Turkey' },
  { code: 'TKM', name: 'Turkmenistan' },
  { code: 'TUV', name: 'Tuvalu' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'DXB', name: 'United Arab Emirates' },
  { code: 'GBR', name: 'United Kingdom' },
  { code: 'USA', name: 'United States' },
  { code: 'URY', name: 'Uruguay' },
  { code: 'UZB', name: 'Uzbekistan' },
  { code: 'VUT', name: 'Vanuatu' },
  { code: 'VAT', name: 'Vatican City' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'VNM', name: 'Vietnam' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'ZMB', name: 'Zambia' },
  { code: 'ZWE', name: 'Zimbabwe' },
];

const ALPHA2_TO_3: Record<string, string> = {
  AE: 'DXB', SA: 'SAU', QA: 'QAT', KW: 'KWT', OM: 'OMN', BH: 'BHR',
  IN: 'IND', PK: 'PAK', BD: 'BGD', LK: 'LKA', NP: 'NPL', PH: 'PHL',
  CN: 'CHN', HK: 'HKG', SG: 'SGP', MY: 'MYS', TH: 'THA', JP: 'JPN', KR: 'KOR',
  GB: 'GBR', IE: 'IRL', FR: 'FRA', DE: 'DEU', ES: 'ESP', IT: 'ITA',
  NL: 'NLD', BE: 'BEL', CH: 'CHE', AT: 'AUT', SE: 'SWE', NO: 'NOR',
  DK: 'DNK', FI: 'FIN', PL: 'POL', TR: 'TUR', RU: 'RUS', EG: 'EGY',
  ZA: 'ZAF', KE: 'KEN', NG: 'NGA', AU: 'AUS', NZ: 'NZL', CA: 'CAN',
  MX: 'MEX', BR: 'BRA', AR: 'ARG', US: 'USA',
};

// Legacy aliases — inputs we still want to silently rewrite. Keeps historical
// rows that were saved as ARE rendering correctly under the DXB convention.
const CODE_ALIASES: Record<string, string> = {
  ARE: 'DXB',
};

export function normalizeCountryCode(input?: string | null): string {
  if (!input) return '';
  const v = input.trim().toUpperCase();
  if (v.length === 3) return CODE_ALIASES[v] ?? v;
  if (v.length === 2) return ALPHA2_TO_3[v] ?? v;
  return v;
}

const COUNTRY_KEYWORDS: { code: string; patterns: RegExp[] }[] = [
  { code: 'DXB', patterns: [/\bU\.?A\.?E\.?\b/i, /\bUnited\s+Arab\s+Emirates\b/i, /\bDubai\b/i, /\bAbu\s*Dhabi\b/i, /\bSharjah\b/i, /\bAjman\b/i, /\bRas\s+al[-\s]?Khaimah\b/i, /\bFujairah\b/i, /\bUmm\s+al[-\s]?Quwain\b/i] },
  { code: 'SAU', patterns: [/\bSaudi\s+Arabia\b/i, /\bKSA\b/, /\bRiyadh\b/i, /\bJeddah\b/i, /\bDammam\b/i, /\bMecca\b/i, /\bMedina\b/i] },
  { code: 'QAT', patterns: [/\bQatar\b/i, /\bDoha\b/i] },
  { code: 'KWT', patterns: [/\bKuwait\b/i] },
  { code: 'OMN', patterns: [/\bOman\b/i, /\bMuscat\b/i] },
  { code: 'BHR', patterns: [/\bBahrain\b/i, /\bManama\b/i] },
  { code: 'IND', patterns: [/\bIndia\b/i, /\bMumbai\b/i, /\bDelhi\b/i, /\bBangalore\b/i, /\bBengaluru\b/i, /\bKochi\b/i, /\bChennai\b/i, /\bKolkata\b/i, /\bHyderabad\b/i, /\bKerala\b/i] },
  { code: 'PAK', patterns: [/\bPakistan\b/i, /\bKarachi\b/i, /\bLahore\b/i, /\bIslamabad\b/i] },
  { code: 'BGD', patterns: [/\bBangladesh\b/i, /\bDhaka\b/i] },
  { code: 'LKA', patterns: [/\bSri\s+Lanka\b/i, /\bColombo\b/i] },
  { code: 'NPL', patterns: [/\bNepal\b/i, /\bKathmandu\b/i] },
  { code: 'PHL', patterns: [/\bPhilippines\b/i, /\bManila\b/i] },
  { code: 'CHN', patterns: [/\bChina\b/i, /\bShanghai\b/i, /\bBeijing\b/i, /\bShenzhen\b/i, /\bGuangzhou\b/i] },
  { code: 'HKG', patterns: [/\bHong\s+Kong\b/i] },
  { code: 'SGP', patterns: [/\bSingapore\b/i] },
  { code: 'MYS', patterns: [/\bMalaysia\b/i, /\bKuala\s+Lumpur\b/i] },
  { code: 'THA', patterns: [/\bThailand\b/i, /\bBangkok\b/i] },
  { code: 'JPN', patterns: [/\bJapan\b/i, /\bTokyo\b/i, /\bOsaka\b/i] },
  { code: 'KOR', patterns: [/\bSouth\s+Korea\b/i, /\bSeoul\b/i] },
  { code: 'GBR', patterns: [/\bUnited\s+Kingdom\b/i, /\bU\.?K\.?\b/, /\bEngland\b/i, /\bScotland\b/i, /\bWales\b/i, /\bLondon\b/i, /\bManchester\b/i, /\bBirmingham\b/i] },
  { code: 'IRL', patterns: [/\bIreland\b/i, /\bDublin\b/i] },
  { code: 'FRA', patterns: [/\bFrance\b/i, /\bParis\b/i, /\bMarseille\b/i] },
  { code: 'DEU', patterns: [/\bGermany\b/i, /\bBerlin\b/i, /\bMunich\b/i, /\bHamburg\b/i] },
  { code: 'ESP', patterns: [/\bSpain\b/i, /\bMadrid\b/i, /\bBarcelona\b/i] },
  { code: 'ITA', patterns: [/\bItaly\b/i, /\bRome\b/i, /\bMilan\b/i] },
  { code: 'NLD', patterns: [/\bNetherlands\b/i, /\bAmsterdam\b/i, /\bRotterdam\b/i] },
  { code: 'BEL', patterns: [/\bBelgium\b/i, /\bBrussels\b/i] },
  { code: 'CHE', patterns: [/\bSwitzerland\b/i, /\bZurich\b/i, /\bGeneva\b/i] },
  { code: 'AUT', patterns: [/\bAustria\b/i, /\bVienna\b/i] },
  { code: 'SWE', patterns: [/\bSweden\b/i, /\bStockholm\b/i] },
  { code: 'NOR', patterns: [/\bNorway\b/i, /\bOslo\b/i] },
  { code: 'DNK', patterns: [/\bDenmark\b/i, /\bCopenhagen\b/i] },
  { code: 'FIN', patterns: [/\bFinland\b/i, /\bHelsinki\b/i] },
  { code: 'POL', patterns: [/\bPoland\b/i, /\bWarsaw\b/i] },
  { code: 'TUR', patterns: [/\bTurkey\b/i, /\bIstanbul\b/i, /\bAnkara\b/i] },
  { code: 'RUS', patterns: [/\bRussia\b/i, /\bMoscow\b/i] },
  { code: 'EGY', patterns: [/\bEgypt\b/i, /\bCairo\b/i] },
  { code: 'ZAF', patterns: [/\bSouth\s+Africa\b/i, /\bJohannesburg\b/i, /\bCape\s+Town\b/i] },
  { code: 'KEN', patterns: [/\bKenya\b/i, /\bNairobi\b/i] },
  { code: 'NGA', patterns: [/\bNigeria\b/i, /\bLagos\b/i, /\bAbuja\b/i] },
  { code: 'AUS', patterns: [/\bAustralia\b/i, /\bSydney\b/i, /\bMelbourne\b/i] },
  { code: 'NZL', patterns: [/\bNew\s+Zealand\b/i, /\bAuckland\b/i, /\bWellington\b/i] },
  { code: 'CAN', patterns: [/\bCanada\b/i, /\bToronto\b/i, /\bVancouver\b/i, /\bMontreal\b/i] },
  { code: 'MEX', patterns: [/\bMexico\b/i] },
  { code: 'BRA', patterns: [/\bBrazil\b/i, /\bSao\s+Paulo\b/i, /\bRio\s+de\s+Janeiro\b/i] },
  { code: 'ARG', patterns: [/\bArgentina\b/i, /\bBuenos\s+Aires\b/i] },
  { code: 'USA', patterns: [/\bU\.?S\.?A?\.?\b/, /\bUnited\s+States\b/i, /\bNew\s+York\b/i, /\bLos\s+Angeles\b/i, /\bChicago\b/i, /\bHouston\b/i, /\bMiami\b/i, /\bDallas\b/i, /\bSan\s+Francisco\b/i] },
];

export function inferCountryCode(text: string): string | null {
  if (!text) return null;
  for (const { code, patterns } of COUNTRY_KEYWORDS) {
    if (patterns.some((p) => p.test(text))) return code;
  }
  const trailingIso3 = /[\s,]([A-Za-z]{3})\s*$/.exec(text.trim());
  if (trailingIso3) return normalizeCountryCode(trailingIso3[1]);
  const trailingIso2 = /[\s,]([A-Za-z]{2})\s*$/.exec(text.trim());
  if (trailingIso2) return normalizeCountryCode(trailingIso2[1]);
  return null;
}
